if(NOT DEFINED BROCCOLI_PLUGIN_RUNTIME_SOURCE OR
   BROCCOLI_PLUGIN_RUNTIME_SOURCE STREQUAL "")
  return()
endif()

if(NOT DEFINED BROCCOLI_PLUGIN_RUNTIME_DESTINATION OR
   BROCCOLI_PLUGIN_RUNTIME_DESTINATION STREQUAL "")
  message(FATAL_ERROR "BROCCOLI_PLUGIN_RUNTIME_DESTINATION is required.")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E copy_if_different
          "${BROCCOLI_PLUGIN_RUNTIME_SOURCE}"
          "${BROCCOLI_PLUGIN_RUNTIME_DESTINATION}"
  COMMAND_ERROR_IS_FATAL ANY
)
